### ISSUE TITLE
Using other languages than supported

### ISSUE THREAD

**Issue by hekl** [NatLibFi/maui#4]
I would like to have support for the Dutch language in Maui. At least it should be possible to use another language than the supported ones with a standard tokenizer (like the standardanalyzer in annif) and no use of stemmers or stopwords. Now this seems to be impossible. Setting stemmers and stopwords to null will invoke a missing class exception for one or the other.

**Comment by osma** [comment]
There is a [NoStemmer](https://github.com/NatLibFi/maui/blob/master/src/main/java/com/entopix/maui/stemmers/NoStemmer.java) class in Maui, did you test it?

Though Stopwords will still be a problem. The [current ones](https://github.com/NatLibFi/maui/tree/master/src/main/java/com/entopix/maui/stopwords) are all specific to some language (except the base class Stopwords, which could be initialized from a file, but only when it is created in Java code). There could be a similar NoStopwords class. Would you like to implement it?

**Comment by hekl** [comment]
I did test the NoStemmer class, but then it complained about the absence of the stopwords class. So, yes if you could implement some NoStopwords class. I hope that will work, because it always recoginizes the @nl language signs in the subjects list.

**Comment by osma** [comment]
Would you be willing/able to do a PR implementing this? It's not a lot of code. For comparison, here is [the commit](https://github.com/NatLibFi/maui/commit/d1e1fbb674a4cf97c17c3af2e0bda5e99561d9fd) that added a Swedish stemmer (snowball based) and stopwords list.

**Comment by hekl** [comment]
Yes, sure.

**Comment by hekl** [comment]
Maybe I misunderstood you, but I am not a Java programmer. I am willing to contribute ideas, test things etc.

**Comment by mjsuhonos** [comment]
Hi @hekl, if you can identify the best list of Dutch stop words to use from this repo, I would be happy to try to put together a Dutch stemmer class for Maui.

https://github.com/stopwords-iso/stopwords-nl

**Comment by osma** [comment]
That's a very nice offer @mjsuhonos!

For my part, I implemented a simple NoStopwords class in PR #8 - it should be better than nothing but surely a DutchStopwords class would be better for @hekl and other Dutch users.

**Comment by hekl** [comment]
This will be a very comprehensive set of stopwords: https://github.com/stopwords-iso/stopwords-nl/blob/master/stopwords-nl.txt.
Thanks, [@mjsuhonos ](https://github.com/mjsuhonos).
